- name: "Install i3 and addtitional for this"
  hosts: localhost
  connection: local
  tasks:

  - name: "install packages to build i3"
    become: true
    apt:
      name: [
        "python3",
        "python3-pip",
        "python3-setuptools",
        "python3-wheel",
        "meson",
        "libstartup-notification0-dev",
        "libxcb-xkb-dev",
        "libxcb-randr0-dev",
        "libxcb-util0-dev",
        "libxcb-cursor-dev",
        "libxcb-keysyms1-dev",
        "libxcb-icccm4-dev",
        "libxcb-xrm-dev",
        "libxkbcommon-dev",
        "libxkbcommon-x11-dev",
        "libyajl-dev",
        "libcairo2-dev",
        "librust-pangocairo-dev"
      ]

  - name: "clone repository of i3"
    ansible.builtin.git:
      repo: 'https://github.com/i3/i3'
      dest: /tmp/i3

  - name: "create build folder"
    shell:
      cmd: "mkdir -p build"
      chdir: /tmp/i3

  - name: "build with meson"
    shell:
      cmd: "meson .."
      chdir: /tmp/i3/build

  - name: "ninja build"
    shell:
      cmd: "ninja"
      chdir: /tmp/i3/build

  - name: "copy i3 binaries to bin folder"
    ansible.builtin.copy:
      src: /tmp/i3/build/i3
      dest: /usr/bin/i3
      group: root
      owner: root
      mode: '0755'

  - name: "copy i3bar binaries to bin folder"
    ansible.builtin.copy:
      src: /tmp/i3/build/i3bar
      dest: /usr/bin/i3bar
      group: root
      owner: root
      mode: '0755'

  - name: "copy i3-config-wizard binaries to bin folder"
    ansible.builtin.copy:
      src: /tmp/i3/build/i3-config-wizard
      dest: /usr/bin/i3-config-wizard
      group: root
      owner: root
      mode: '0755'

  - name: "copy i3-msg binaries to bin folder"
    ansible.builtin.copy:
      src: /tmp/i3/build/i3-msg
      dest: /usr/bin/i3-msg
      group: root
      owner: root
      mode: '0755'

  - name: "copy i3-nagbar binaries to bin folder"
    ansible.builtin.copy:
      src: /tmp/i3/build/i3-nagbar
      dest: /usr/bin/i3-nagbar
      group: root
      owner: root
      mode: '0755'

